SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_KINDS = 3
ASTEROID_MIN_RADIUS = 20
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_MAX_SPAWN = 20
ASTEROID_SPAWN_RATE = 0.8  # seconds

PLAYER_RADIUS = 20
PLAYER_SPEED = 200
PLAYER_SPEED_BOOST = PLAYER_SPEED * 3
PLAYER_SPEED_BOOST_COOLDOWN = 5
PLAYER_SPEED_BOOST_DURATION = 1
PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3
PLAYER_TURN_SPEED = 300

SHOT_RADIUS = 5